skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
programs_usefect = "FLYaSSPbQKzqq3BYNF7Jgn7CxPyEK7YTtr8jMmQtivfa"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
